config/routes.rb
DnfTeam::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'dashboard#index'

  scope path: 'remote' do
    resources :popups, only: :show
    resource :order, only: :create
  end

  devise_scope :user do
    get 'users/:id' => 'users#show', as: :user
    put '/users/:id/update' => 'users#update', as: :update_user_profile
  end

  get ':id' => 'static_pages#show', as: :static_page

  resources :lessons, :users, only: :show
end

app/models/user.rb
# User model
class User < ActiveRecord::Base
  extend FriendlyId

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :delete_image

  friendly_id :nickname, use: [:slugged, :finders]

  belongs_to :guild

  has_many :lessons
  has_many :advertisement
  has_many :articles
  has_many :rank_histories
  has_many :award_histories

  has_many :ranks,  through: :rank_histories
  has_many :awards, through: :award_histories

  has_and_belongs_to_many :groups

  has_attached_file :avatar,
                    styles: {
                      thumb: '100x100>',
                      regular: '200x200>'
                    },
                    default_url: 'missing.png'

  validates :email, :nickname, presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  include Granteable

  before_save :set_uniqueness_nickname, if: [:nickname, :nickname_changed?]
  before_save :destroy_image?
  before_save :set_role

  # get user's fullname
  def fullname
    [name, patronymic, surname].delete_if(&:blank?).join(' ')
  end

  # get user's labelname
  def label_name
    nickname.presence || fullname.presence || 'Аноним'
  end

  # user's name setter
  def fullname=(str)
    str = str.split(' ')
    self.name = str.shift
    self.patronymic = str.shift
    self.surname = str.shift
  end

  private

  # setting role from group
  def set_role
    self.role = groups.map(&:role).sort_by { |x| %w(root admin user).index(x) }.first
  end

  # checking for uniqueness of nickname
  def set_uniqueness_nickname
    nicknames = User.select(:nickname).map(&:nickname)
    return unless nickname.in? nicknames
    i = 0
    while nickname.in? nicknames
      self.nickname += i.to_s
      i += 1
    end
  end

  # checking for destroying image
  def destroy_image?
    avatar.clear if @delete_image == '1'
  end
end

app/controllers/users_controller.rb
# Users controller
class UsersController < Devise::RegistrationsController
  include Devise::Controllers::Helpers

  before_action :set_user

  # user profile viewing
  def show
    @user = User.find(params[:id])
    metatags(@user)
  end

  # user editing
  def edit
  end

  # изменение
  def update
    result = @user.update(user_params)
    if user_params[:password] || user_params[:email]
      flash[:notice] = 'Профиль обновлен. Пожалуйста, войдите на сайт еще раз.'
      sign_out_and_redirect(@user)
    else
      flash[:notice] = 'Профиль обновлен.'
      redirect_to(result ? user_path(@user) : :back)
    end
  end

  # getting current user
  def set_user
    @user = current_user
  end

  private

  # параметры
  def user_params
    params.require(:user).permit(
      :id, :email, :password, :encrypted_password, :password_confirmation, :avatar, :name, :patronymic,
      :surname, :hardware, :location, :birthday, :subscription, :avatar_content_type, :avatar_file_size,
      :avatar_file_name, :country, :reset_password_token, :reset_password_sent_at, :nickname, :experience,
      :contacts, :languages, :available_days, :dialog_time, :delete_image, :fullname
    )
  end
end

app/views/users/_restore_password.html.slim
#restorePassword.popup
  .popup-inner
    .close.close-popup
      span
    .title восстановить пароль
    = simple_form_for :user, url: password_path(:user), html: { id: 'new_user',  }, method: :post do |f|
      = f.input :email, input_html: { placeholder: 'E-mail' }
      = f.submit 'выслать новый пароль'

app/views/users/show.html.slim
.page-inner.content-center
  h1
    = @user.nickname
  .time-enter
    | Был на сайте #{@user.last_sign_in_at.formatted}
    span.hr1.hr4
    span.time-bl.light Дата регистрации: #{@user.created_at.formatted}
  .profile-block
    .avatar-block
      - if user_signed_in? && current_user.id.eql?(@user.id)
        = simple_form_for @user, url: update_user_profile_path(@user), method: :put, defaults: { wrapper: false, label: false }, html: { name: 'user_form', id: 'edit_user' } do |form|
          = image_tag @user.avatar.url(:regular), alt: '', title: '', id: 'avatar'
          .file-inp.relative
            input#remote_check type='hidden' name='remote' value='1'
            = form.input :avatar
            = form.input :delete_image, as: :hidden, input_html: { value: 0 }
            a href='#'
              span Изменить аватар
          p.light максимальный размер 200х200
          #deleteAvatar.close title='удалить аватар'
            span
      - else
        = image_tag @user.avatar.url
    table
      tr
        th Имя, отчество:
        td
          = @user.fullname
      tr
        th Звание:
        td = @user.ranks.map(&:name).try(:join, ', ')
      tr
        th Дата рождения:
        td
          = @user.birthday.try(:strftime, '%d.%m.%Y')
      tr
        th Страна, город:
        td
          = @user.location
      tr
        th Тех. оснащение:
        td
          = @user.hardware
      tr
        th Подпись:
        td
          = @user.subscription
  .hr3
  - if user_signed_in? && current_user.id.eql?(@user.id)
    .profile-edit-block.clearfix
      = link_to 'Редактировать профиль', edit_user_registration_path, class: 'btn btn-profile'
      = link_to '#', 'data-url' => popup_path(:email), 'data-href' => 'changeEmail', class: 'email-pr linkPopup' do
        i
        span Изменить E-mail
      = link_to '#', 'data-url' => popup_path(:password), 'data-href' => 'changePassword', class: 'password-pr linkPopup' do
        i
        span Изменить пароль
#changeEmail.popup
#changePassword.popup