config/routes.rb
DnfTeam::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'dashboard#index'

  scope path: 'remote' do
    resources :popups, only: :show
    resource :order, only: :create
  end

  devise_scope :user do
    get 'users/:id' => 'users#show', as: :user
    put '/users/:id/update' => 'users#update', as: :update_user_profile
  end

  get ':id' => 'static_pages#show', as: :static_page

  resources :lessons, :users, only: :show
end

app/models/ability.rb
# Abilities class
class Ability
  include CanCan::Ability

  # initializer
  def initialize(user)
    return unless user
    if user.role != 'user'
      can :access, :rails_admin
      can :dashboard
      can :manage, :all
    else
      can :manage, :user, role: 'user'
    end
  end
end

app/models/advertisement.rb
# Advertisement class
class Advertisement < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
end

app/models/article.rb
# Article class
class Article < ActiveRecord::Base
  belongs_to :user

  has_and_belongs_to_many :groups

  validates :name, presence: true

  before_save :default_groups

  private

  # set default groups
  def default_groups
    self.groups = Group.all if groups.blank?
  end

  include Granteable
end

app/models/award.rb
# Award history
class Award < ActiveRecord::Base
  has_many :award_histories
  has_many :users, through: :award_histories
end

app/models/award_history.rb
# Awards history model
class AwardHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :award
end

app/models/category.rb
# Category class
class Category < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  has_many :lessons

  has_and_belongs_to_many :groups

  validates :name, presence: true

  include Granteable
end

app/models/dashboard_image.rb
# Dashboard images class
class DashboardImage < ActiveRecord::Base

  has_attached_file :attach,
                    styles: { content: '1920х600' },
                    url:  '/system/dashboard_images/:id/:filename',
                    path: ':rails_root/public/system/dashboard_images/:id/:filename'

  validates_attachment_presence :attach
  validates_attachment_size :attach, less_than: 2.megabytes
  validates_attachment_content_type :attach, content_type: /\Aimage/

  after_save :set_interval

  private

  # Setting slider speed
  def set_interval
    self.class.skip_callback :save, :after, :set_interval
    images = DashboardImage.where.not(id: id)
    if interval.blank?
      self.interval = images.first.interval
      save
    else
      images.each do |image|
        image.update(interval: interval)
      end
    end
    self.class.set_callback :save, :after, :set_interval
  end
end

app/models/email.rb
# Email class
class Email < ActiveRecord::Base
  belongs_to :guild

  validates :value, presence: true
end

app/models/group.rb
# Users group class
class Group < ActiveRecord::Base
  extend Enumerize

  enumerize :role, in: %w(root admin user)

  has_and_belongs_to_many :users
  has_and_belongs_to_many :static_pages
  has_and_belongs_to_many :lessons
  has_and_belongs_to_many :guilds
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :lesson_categories

  scope :defaults, -> { where(is_default: true) }

  after_save :update_users_role, if: :role_changed?

  private

  # set user role from group
  def update_users_role
    users.each { |u| u.save validate: false }
  end
end

app/models/guild.rb
# Guild class
class Guild < ActiveRecord::Base
  has_attached_file :image, styles: { small: 'x81' }

  has_many :emails
  has_many :users

  has_and_belongs_to_many :groups

  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :name, :link, :structure, :orders, :charter, presence: true
  validates :emails, presence: true, if: :in_order

  scope :for_order, -> { where(in_order: true) }

  include Granteable
end

app/models/lesson.rb
# Lessons class
class Lesson < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  belongs_to :category
  belongs_to :user
  belongs_to :lesson_category

  has_many :lesson_categories

  has_and_belongs_to_many :groups

  validates :name, :user, presence: true

  include Granteable
end

app/models/lesson_category.rb
# Lessons categories class
class LessonCategory < ActiveRecord::Base
  belongs_to :lesson

  has_many :lessons

  has_and_belongs_to_many :groups

  validates :name, presence: true

  include Granteable
end

app/models/link.rb
# Links module
class Link < ActiveRecord::Base
  extend Enumerize

  enumerize :mode, in: %w(email channel vk)

  validates :mode, :title, :url, presence: true

  scope :find_by_mode, -> (mode) { where(mode: mode) }
end

app/models/order.rb
# Order class
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :guild

  validates :guild_id, presence: true
end

app/models/rank.rb
# Ranks class
class Rank < ActiveRecord::Base
  has_many :rank_histories
  has_many :users, through: :rank_histories
end

app/models/rank_history.rb
# Rank history class
class RankHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :rank
end

app/models/seo_url.rb
# Модель метатегов по ссылкам
class SeoUrl < ActiveRecord::Base
  has_many :urls

  validates :urls, presence: true
end

app/models/static_page.rb
# Static pages class
class StaticPage < ActiveRecord::Base
  extend FriendlyId

  has_and_belongs_to_many :groups

  friendly_id :name, use: [:slugged, :finders]

  validates :content, :name, presence: true

  include Granteable
end

app/models/url.rb
# Url model
class Url < ActiveRecord::Base
  belongs_to :seo_url

  validates :value, presence: true
end

app/models/user.rb
# User model
class User < ActiveRecord::Base
  extend FriendlyId

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :delete_image

  friendly_id :nickname, use: [:slugged, :finders]

  belongs_to :guild

  has_many :lessons
  has_many :advertisement
  has_many :articles
  has_many :rank_histories
  has_many :award_histories

  has_many :ranks,  through: :rank_histories
  has_many :awards, through: :award_histories

  has_and_belongs_to_many :groups

  has_attached_file :avatar,
                    styles: {
                      thumb: '100x100>',
                      regular: '200x200>'
                    },
                    default_url: 'missing.png'

  validates :email, :nickname, presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  include Granteable

  before_save :set_uniqueness_nickname, if: [:nickname, :nickname_changed?]
  before_save :destroy_image?
  before_save :set_role

  # get user's fullname
  def fullname
    [name, patronymic, surname].delete_if(&:blank?).join(' ')
  end

  # get user's labelname
  def label_name
    nickname.presence || fullname.presence || 'Аноним'
  end

  # user's name setter
  def fullname=(str)
    str = str.split(' ')
    self.name = str.shift
    self.patronymic = str.shift
    self.surname = str.shift
  end

  private

  # setting role from group
  def set_role
    self.role = groups.map(&:role).sort_by { |x| %w(root admin user).index(x) }.first
  end

  # checking for uniqueness of nickname
  def set_uniqueness_nickname
    nicknames = User.select(:nickname).map(&:nickname)
    return unless nickname.in? nicknames
    i = 0
    while nickname.in? nicknames
      self.nickname += i.to_s
      i += 1
    end
  end

  # checking for destroying image
  def destroy_image?
    avatar.clear if @delete_image == '1'
  end
end

app/controllers/popups_controller.rb
# Popups for ordering, entering and registration
class PopupsController < ApplicationController
  # show popup
  def show
    if params[:id].eql? 'registration'
      @user = User.new
    elsif params[:id].in? %w(email password)
      @user = current_user
    elsif params[:id].eql? 'order'
      @order = Order.new(user_id: current_user.try(:id))
      @guild = Guild.find(params[:guild]) if params[:guild]
    end
    render params[:id], layout: false
  end
end

app/views/popups/email.html.slim
.popup-inner
  .close.close-popup
    span
  .title Изменить E-mail
  = simple_form_for @user, url: update_user_profile_path(@user), method: :put, \
    defaults: { wrapper: false, label: false }, html: { name: 'user_form', id: 'edit_user' } do |f|
    = f.input :email, input_html: { value: @user.email, placeholder: 'Новый e-mail' }
    = f.submit 'сменить'

app/views/popups/login.html.slim
.popup-inner
  .close.close-popup
    span
  .title Вход
  = simple_form_for :user, url: session_path(:user), defaults: { label: false, wrapper: false } do |f|
    = f.input :email, input_html: { placeholder: 'E-mail' }
    = f.input :password, input_html: { placeholder: 'Пароль' }
    = f.submit 'Войти'
.restore-password
  = link_to 'Восстановить пароль', new_password_path(:user)

app/views/popups/order.html.slim
.popup-inner
  .close.close-popup
    span
  .title Заявка на вступление
  = simple_form_for @order, url: order_path, method: :post, remote: true, \
    defaults: { label: false, wrapper: false, as: :string } do |f|
    = f.input :user_id, as: :hidden, input_html: { value: @order.user_id }
    - if @guilds.present?
      .choice
        ul
          - @guilds.for_order.each_with_index do |guild, i|
            li
              label class="label_radio #{'r_on' if guild.id.eql?(@guild.try(:id))}" for="order_guild_id_#{i+1}"
                = radio_button_tag 'order[guild_id]', guild.id, false, { class: 'guild', checked: guild.id.eql?(@guild.try(:id)) }
                span.block
                  = image_tag guild.image.url(:small), alt: guild.name, title: guild.name
                span.block
                  span
                    = guild.name
    - if @guild
      .link-rules
        ul
          li
            = link_to 'Устав', @guild.charter, id: 'charter-link'
          li
            = link_to 'Структура', @guild.structure, id: 'structure-link'
          li
            = link_to 'Орг. приказы', @guild.orders, id: 'orders-link'

    - [[:name, 'Имя Отчество'], [:hardware, 'Техническое оснащение']].delete_if { |f| @guild.present? && !@guild.send("is_#{f[0]}")}.each do |field|
      = f.input field[0], input_html: { placeholder: field[1], required: true, value: current_user.try(:send, field[0]), class: 'order_field' }
    
    = f.input :birthday, input_html: { placeholder: 'Дата рождения', \
      value: current_user.try(:birthday).try(:strftime, '%d.%m.%Y'), class: 'order_field' }
    
    - [[:location, 'Место жительства (страна, город, часовой пояс)'], [:nickname, 'Позывной']].delete_if { |f| @guild.present? && !@guild.send("is_#{f[0]}")}.each do |field|
      = f.input field[0], input_html: { placeholder: field[1], required: true, value: current_user.try(:send, field[0]), class: 'order_field' }

    - [[:experience, 'Срок налета оффлайн/онлайн'], [:contacts, 'Контактная информация'], [:languages, 'Знание иностранных языков'], [:available_days, 'Возможность летать Вт, Чт, Вс после 21.00 МСК'], [:dialog_time, 'Удобное время для собеседования']].delete_if { |f| @guild.present? && !@guild.send("is_#{f[0]}")}.each do |field|
      = f.input field[0], input_html: { placeholder: field[1], required: true, class: 'order_field' }
    div.rules_check
      label for='rules' class='label_check'
        input id='rules' type='checkbox' name='rules' value='1'
        i
        span 
          | &nbsp;
          | С уставом ознакомлен
    - if @guild.present?
      = f.submit 'Отправить', style: 'display: none', id: 'registration_submit'
javascript:
  $('.rules_check').hide();
  initializeMask();

app/views/popups/password.html.slim
.popup-inner
  .close.close-popup
    span
  .title изменить пароль
  = simple_form_for @user, url: update_user_profile_path(@user), method: :put, defaults: { wrapper: false, label: false } do |form|
    = form.input :password, input_html: { placeholder: 'Пароль' }
    = form.input :password_confirmation, input_html: { placeholder: 'Пароль' }
    = form.submit 'Сменить пароль'

app/views/popups/registration.html.slim
.popup-inner
  .close.close-popup
    span
  .title Регистрация
  = simple_form_for(@user, url: registration_path(@user), defaults: { label: false, wrapper: false, as: :string }) do |f|
    = f.input :email, input_html: { placeholder: 'E-mail', required: true, autofocus: true }
    = f.input :nickname, input_html: { placeholder: 'Позывной', required: true }
    = f.input :password, as: :password, input_html: { placeholder: 'Пароль', required: true }
    = f.input :password_confirmation, as: :password, input_html: { placeholder: 'Еще раз пароль', required: true }
    .show-more
      = link_to '#', id: 'additionalFields', class: 'more'
        span дополнительные поля
    #moreField.hide
      = f.input :name, input_html: { placeholder: 'Имя' }
      = f.input :surname, input_html: { placeholder: 'Фамилия' }
      = f.input :patronymic, input_html: { placeholder: 'Отчество' }
      = f.input :birthday, input_html: { placeholder: 'Дата рождения' }
      = f.input :subscription, input_html: { placeholder: 'Подпись' }
    = f.submit 'Зарегистрироваться'